---
version: '2'
services:
  mysql55:
    image: mysql:5.5
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row" ]
    networks:
      default:
        aliases:
          - mysql55
    environment:
      MYSQL_ROOT_PASSWORD: numtel

  mysql56:
    image: mysql:5.6
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row" ]
    networks:
      default:
        aliases:
          - mysql56
    environment:
      MYSQL_ROOT_PASSWORD: numtel

  mysql57:
    image: mysql:5.7
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row" ]
    networks:
      default:
        aliases:
          - mysql57
    environment:
      MYSQL_ROOT_PASSWORD: numtel

  mysql83:
    image: mysql:8.3
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row", "--default-authentication-plugin=caching_sha2_password" ]
    ports:
      - "3308:3306"
    networks:
      default:
        aliases:
          - mysql83
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
